version: '3.7'
services:
  db:
    image: mysql
    container_name: springboot2_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - io_github_batetolast1:/var/lib/mysql
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
volumes:
  io_github_batetolast1: