server:
  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
#        [org.hibernate.SQL_SLOW] LOG
#        session:
#          events:
#            log:
#              LOG_QUERIES_SLOWER_THAN_MS: 20

logging:
  level:
    org:
      #     JPA Queries
      hibernate:
        SQL: TRACE
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      #     JdbcTemplate
      springframework:
        jdbc:
          core:
            JdbcTemplate: TRACE
            StatementCreatorUtils: TRACE